# FROM alpine:3.14
# CMD ["echo", "Eu sou uma pessoa estudante da Trybe!"]

# FROM alpine:3.14
# CMD ["echo", "Olá Mundo!"]

# FROM alpine:3.14
# ENTRYPOINT ["echo", "Olá mundo!"]

FROM alpine:3.14
ENTRYPOINT ["echo"]
CMD ["Sou a mensagem padrão."]